[package]
name = "stock_simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
rand = "0.9.0"
itertools = "0.14.0"
build_html = "2.6.0"
structopt = { version = "0.3", default-features = false}
