[package]
name = "stock_simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
rand = "0.8.5"
itertools = "0.13.0"
build_html = "2.5.0"
structopt = { version = "0.3", default-features = false}
